In [2]:
import pandas as pd

In [3]:
df = pd.read_parquet('data/interim/dashboard_events.parquet')
df

,timestamp,user,method,endpoint,status,dashboard_id,path,browser,browser_platform,browser_version,date
0,2018-08-09 14:00:00,b1fababf379ab3d8@project-a.com,GET,dashboards.view_dashboard,200,marketing-overview,/dashboards/marketing-overview,chrome,macos,67.0.3396.99,2018-08-09
1,2018-08-09 15:00:00,9bfa5deadc8f2d7d@project-a.com,GET,dashboards.view_dashboard,200,marketing-overview,/dashboards/marketing-overview,chrome,macos,67.0.3396.99,2018-08-09
2,2018-08-09 15:00:00,adacf3b44f8b4dc4@project-a.com,GET,dashboards.view_dashboard,200,marketing-overview,/dashboards/marketing-overview,firefox,linux,61.0,2018-08-09
3,2018-08-09 15:00:00,b1fababf379ab3d8@project-a.com,GET,dashboards.view_dashboard,200,marketing-overview,/dashboards/marketing-overview,chrome,macos,67.0.3396.99,2018-08-09
4,2018-08-09 16:00:00,77a89f0341001421@project-a.com,GET,dashboards.view_dashboard,200,marketing-overview,/dashboards/marketing-overview,chrome,macos,67.0.3396.99,2018-08-09
...,...,...,...,...,...,...,...,...,...,...,...
460,2018-09-06 10:00:00,13f7e9ada41f2425@lampenwelt.de,GET,dashboards.view_dashboard,200,marketing-crm-scorecard,/dashboards/marketing-crm-scorecard,chrome,windows,68.0.3440.106,2018-09-06
461,2018-09-06 10:00:00,e5063e1f25c24f00@lampenwelt.de,GET,dashboards.view_dashboard,200,shop-performance-overview,/dashboards/shop-performance-overview,chrome,windows,68.0.3440.106,2018-09-06
462,2018-09-06 10:00:00,e5063e1f25c24f00@lampenwelt.de,GET,dashboards.view_dashboard,200,marketing-country-overview,/dashboards/marketing-country-overview,chrome,windows,68.0.3440.106,2018-09-06
463,2018-09-06 10:00:00,3a11c5eae09adb43@lampenwelt.de,GET,dashboards.view_dashboard,200,marketing-channel-overview,/dashboards/marketing-channel-overview,chrome,windows,68.0.3440.106,2018-09-06
464,2018-09-06 11:00:00,b1fababf379ab3d8@project-a.com,GET,dashboards.view_dashboard,200,marketing-overview,/dashboards/marketing-overview,chrome,macos,68.0.3440.106,2018-09-06

seemes like some files are not loading properly. i only get few months...

In [7]:
import os

base_path = "data/raw/requests"
max_depth = 5

for root, dirs, files in os.walk(base_path):
    level = root.replace(base_path, "").count(os.sep)

    if level > max_depth:
        dirs[:] = []
        continue

    indent = "  " * level
    print(f"{indent}{os.path.basename(root)}/")

    sub_indent = "  " * (level + 1)

    for file in files[:10]:
        print(f"{sub_indent}{file}")

    if len(files) > 10:
        print(f"{sub_indent}... {len(files) - 10} more files")

requests/
  2018/
    08/
      09/
        mara-log/
          requests-14.json
          requests-15.json
          requests-16.json
          requests-17.json
          requests-18.json
          requests-19.json
          requests-22.json
      10/
        mara-log/
          requests-08.json
          requests-09.json
          requests-10.json
          requests-11.json
          requests-12.json
          requests-13.json
          requests-14.json
          requests-15.json
          requests-22.json
          requests-23.json
      11/
        mara-log/
          requests-13.json
      12/
        mara-log/
          requests-09.json
          requests-20.json
          requests-21.json
      13/
        mara-log/
          requests-08.json
          requests-09.json
          requests-10.json
          requests-11.json
          requests-12.json
          requests-13.json
          requests-14.json
          requests-15.json
          requests-16.json
          requests-18.json
      14/
        mara-log/
          requests-08.json
          requests-09.json
          requests-10.json
          requests-11.json
          requests-13.json
          requests-14.json
          requests-15.json
          requests-17.json
          requests-18.json
          requests-19.json
          ... 2 more files
      15/
        mara-log/
          requests-08.json
          requests-09.json
          requests-10.json
          requests-11.json
          requests-12.json
          requests-13.json
          requests-14.json
          requests-16.json
          requests-17.json
          requests-18.json
          ... 1 more files
      16/
        mara-log/
          requests-09.json
          requests-10.json
          requests-11.json
          requests-12.json
          requests-13.json
          requests-15.json
          requests-16.json
          requests-17.json
          requests-18.json
          requests-20.json
          ... 1 more files
      17/
        mara-log/
          requests-08.json
          requests-09.json
          requests-10.json
          requests-12.json
          requests-13.json
          requests-14.json
          requests-15.json
          requests-16.json
          requests-17.json
      19/
        mara-log/
          requests-14.json
          requests-15.json
          requests-16.json
      20/
        mara-log/
          requests-08.json
          requests-09.json
          requests-10.json
          requests-11.json
          requests-12.json
          requests-13.json
          requests-14.json
          requests-15.json
          requests-16.json
          requests-17.json
          ... 3 more files
      21/
        mara-log/
          requests-08.json
          requests-09.json
          requests-10.json
          requests-11.json
          requests-12.json
          requests-13.json
          requests-14.json
          requests-15.json
          requests-16.json
          requests-17.json
          ... 1 more files
      22/
        mara-log/
          requests-10.json
          requests-11.json
          requests-13.json
          requests-14.json
          requests-15.json
      23/
        mara-log/
          requests-12.json
          requests-13.json
          requests-14.json
          requests-15.json
          requests-16.json
      24/
        mara-log/
          requests-07.json
          requests-08.json
          requests-09.json
          requests-10.json
          requests-11.json
          requests-12.json
          requests-13.json
          requests-14.json
          requests-15.json
          requests-16.json
          ... 1 more files
      25/
        mara-log/
          requests-16.json
      27/
        mara-log/
          requests-07.json
          requests-08.json
          requests-09.json
          requests-10.json
          requests-11.json
          requests-12.json
          requests-13.json
          requests-14.json
          requests-15.json
          requests-16.json
          ... 2 more files
      28/
        mara-log/
          requests-08.json
          requests-09.json
          requests-10.json
          requests-11.json
          requests-13.json
          requests-14.json
          requests-15.json
          requests-16.json
          requests-20.json
      29/
        mara-log/
          requests-08.json
          requests-09.json
          requests-10.json
          requests-11.json
          requests-12.json
          requests-13.json
          requests-14.json
          requests-15.json
          requests-17.json
          requests-18.json
          ... 2 more files
      30/
        mara-log/
          requests-08.json
          requests-09.json
          requests-10.json
          requests-11.json
          requests-12.json
          requests-13.json
          requests-14.json
          requests-16.json
          requests-17.json
          requests-18.json
          ... 1 more files
      31/
        mara-log/
          requests-09.json
          requests-10.json
          requests-11.json
          requests-12.json
          requests-13.json
          requests-14.json
          requests-15.json
          requests-16.json
          requests-17.json
          requests-18.json
    09/
      03/
        mara-log/
          requests-08.json
          requests-09.json
          requests-10.json
          requests-11.json
          requests-12.json
          requests-13.json
          requests-14.json
          requests-15.json
          requests-16.json
          requests-17.json
      04/
        mara-log/
          requests-07.json
          requests-08.json
          requests-09.json
          requests-10.json
          requests-11.json
          requests-12.json
          requests-13.json
          requests-14.json
          requests-15.json
          requests-16.json
          ... 2 more files
      05/
        mara-log/
          requests-07.json
          requests-08.json
          requests-09.json
          requests-10.json
          requests-11.json
          requests-12.json
          requests-13.json
          requests-14.json
          requests-15.json
          requests-16.json
          ... 1 more files
      06/
        mara-log/
          requests-08.json
          requests-09.json
          requests-10.json
          requests-11.json
          requests-12.json
          requests-13.json
          requests-14.json
          requests-15.json
          requests-16.json
          requests-17.json
          ... 2 more files
      07/
        mara-log/
          requests-07.json
          requests-09.json
          requests-10.json
          requests-11.json
          requests-12.json
          requests-13.json
          requests-14.json
          requests-15.json
          requests-16.json
          requests-17.json
          ... 2 more files
      08/
        mara-log/
          requests-08.json
      09/
        mara-log/
          requests-15.json
          requests-17.json
          requests-18.json
          requests-20.json
          requests-22.json
      10/
        mara-log/
          requests-08.json
          requests-09.json
          requests-10.json
          requests-11.json
          requests-12.json
          requests-13.json
          requests-14.json
          requests-15.json
          requests-16.json
          requests-17.json
          ... 1 more files
      11/
        mara-log/
          requests-08.json
          requests-09.json
          requests-10.json
          requests-11.json
          requests-12.json
          requests-13.json
          requests-14.json
          requests-15.json
          requests-16.json
          requests-17.json
      12/
        mara-log/
          requests-09.json
          requests-10.json
          requests-11.json
          requests-13.json
          requests-14.json
          requests-15.json
          requests-16.json
          requests-17.json
      13/
        mara-log/
          requests-08.json
          requests-09.json
          requests-10.json
          requests-11.json
          requests-12.json
          requests-13.json
          requests-14.json
          requests-15.json
          requests-16.json
          requests-17.json
          ... 4 more files
      14/
        mara-log/
          requests-08.json
          requests-09.json
          requests-10.json
          requests-11.json
          requests-12.json
          requests-13.json
          requests-14.json
          requests-15.json
          requests-16.json
          requests-17.json
          ... 1 more files
      15/
        mara-log/
          requests-16.json
          requests-17.json
          requests-23.json
      16/
        mara-log/
          requests-10.json
      17/
        mara-log/
          requests-08.json
          requests-09.json
          requests-10.json
          requests-11.json
          requests-12.json
          requests-13.json
          requests-14.json
          requests-15.json
          requests-16.json
          requests-17.json
          ... 1 more files
      18/
        mara-log/
          requests-07.json
          requests-08.json
          requests-09.json
          requests-10.json
          requests-11.json
          requests-12.json
          requests-13.json
          requests-14.json
          requests-16.json
          requests-17.json
      19/
        mara-log/
          requests-08.json
          requests-09.json
          requests-10.json
          requests-11.json
          requests-12.json
          requests-13.json
          requests-14.json
          requests-15.json
          requests-16.json
          requests-17.json
          ... 3 more files
      20/
        mara-log/
          requests-08.json
          requests-09.json
          requests-11.json
          requests-12.json
          requests-13.json
          requests-14.json
          requests-15.json
          requests-16.json
          requests-17.json
          requests-20.json
      21/
        mara-log/
          requests-08.json
          requests-09.json
          requests-10.json
          requests-11.json
          requests-12.json
          requests-13.json
          requests-14.json
          requests-15.json
          requests-16.json
          requests-18.json
      23/
        mara-log/
          requests-20.json
      24/
        mara-log/
          requests-09.json
          requests-10.json
          requests-11.json
          requests-12.json
          requests-13.json
          requests-14.json
          requests-15.json
          requests-16.json
          requests-17.json
          requests-18.json
          ... 4 more files
      25/
        mara-log/
          requests-08.json
          requests-09.json
          requests-10.json
          requests-11.json
          requests-12.json
          requests-13.json
          requests-14.json
          requests-15.json
          requests-16.json
          requests-17.json
          ... 3 more files
      26/
        mara-log/
          requests-08.json
          requests-09.json
          requests-10.json
          requests-11.json
          requests-12.json
          requests-13.json
          requests-15.json
          requests-16.json
          requests-20.json
          requests-21.json
      27/
        mara-log/
          requests-08.json
          requests-09.json
          requests-10.json
          requests-11.json
          requests-12.json
          requests-13.json
          requests-14.json
          requests-15.json
          requests-16.json
          requests-17.json
          ... 5 more files
      28/
        mara-log/
          requests-08.json
          requests-09.json
          requests-10.json
          requests-11.json
          requests-12.json
          requests-13.json
          requests-14.json
          requests-15.json
          requests-16.json
          requests-17.json
          ... 2 more files
      29/
        mara-log/
          requests-19.json
      30/
        mara-log/
          requests-21.json
    10/
      01/
        mara-log/
          requests-07.json
          requests-08.json
          requests-09.json
          requests-10.json
          requests-11.json
          requests-12.json
          requests-13.json
          requests-14.json
          requests-15.json
          requests-16.json
      02/
        mara-log/
          requests-08.json
          requests-09.json
          requests-10.json
          requests-11.json
          requests-12.json
          requests-13.json
          requests-14.json
          requests-16.json
          requests-19.json
      04/
        mara-log/
          requests-09.json
          requests-10.json
          requests-11.json
          requests-12.json
          requests-13.json
          requests-14.json
          requests-15.json
          requests-16.json
          requests-17.json
          requests-18.json
          ... 1 more files
      05/
        mara-log/
          requests-08.json
          requests-09.json
          requests-10.json
          requests-11.json
          requests-12.json
          requests-13.json
          requests-14.json
          requests-15.json
          requests-16.json
      07/
        mara-log/
          requests-17.json
          requests-18.json
          requests-19.json
      08/
        mara-log/
          requests-09.json
          requests-10.json
          requests-11.json
          requests-12.json
          requests-13.json
          requests-14.json
          requests-15.json
          requests-16.json
          requests-18.json
      09/
        mara-log/
          requests-09.json
          requests-10.json
          requests-11.json
          requests-12.json
          requests-13.json
          requests-14.json
          requests-15.json
          requests-16.json
          requests-17.json
          requests-18.json
          ... 2 more files
      10/
        mara-log/
          requests-08.json
          requests-09.json
          requests-10.json
          requests-11.json
          requests-12.json
          requests-13.json
          requests-14.json
          requests-15.json
          requests-16.json
          requests-20.json
          ... 1 more files
      11/
        mara-log/
          requests-07.json
          requests-08.json
          requests-09.json
          requests-10.json
          requests-11.json
          requests-12.json
          requests-13.json
          requests-14.json
          requests-15.json
          requests-16.json
      12/
        mara-log/
          requests-07.json
          requests-08.json
          requests-09.json
          requests-10.json
          requests-11.json
          requests-12.json
          requests-13.json
          requests-14.json
          requests-15.json
          requests-16.json
          ... 1 more files
      14/
        mara-log/
          requests-20.json
      15/
        mara-log/
          requests-08.json
          requests-09.json
          requests-10.json
          requests-11.json
          requests-12.json
          requests-13.json
          requests-14.json
          requests-15.json
          requests-16.json
          requests-18.json
          ... 3 more files
      16/
        mara-log/
          requests-00.json
          requests-08.json
          requests-09.json
          requests-10.json
          requests-11.json
          requests-12.json
          requests-13.json
          requests-14.json
          requests-15.json
          requests-16.json
          ... 1 more files
      17/
        mara-log/
          requests-08.json
          requests-09.json
          requests-10.json
          requests-11.json
          requests-12.json
          requests-13.json
          requests-14.json
          requests-15.json
          requests-16.json
          requests-17.json
          ... 1 more files
      18/
        mara-log/
          requests-07.json
          requests-08.json
          requests-09.json
          requests-10.json
          requests-11.json
          requests-12.json
          requests-13.json
          requests-14.json
          requests-15.json
          requests-16.json
          ... 1 more files
      19/
        mara-log/
          requests-08.json
          requests-09.json
          requests-10.json
          requests-11.json
          requests-12.json
          requests-13.json
          requests-14.json
          requests-15.json
          requests-16.json
          requests-17.json
          ... 1 more files
      22/
        mara-log/
          requests-09.json
          requests-10.json
          requests-11.json
          requests-12.json
          requests-13.json
          requests-14.json
          requests-15.json
          requests-16.json
          requests-17.json
          requests-18.json
      23/
        mara-log/
          requests-09.json
          requests-10.json
          requests-11.json
          requests-12.json
          requests-13.json
          requests-14.json
          requests-15.json
          requests-16.json
      24/
        mara-log/
          requests-09.json
          requests-10.json
          requests-11.json
          requests-12.json
          requests-13.json
          requests-14.json
          requests-15.json
          requests-16.json
      25/
        mara-log/
          requests-07.json
          requests-08.json
          requests-09.json
          requests-10.json
          requests-11.json
          requests-12.json
          requests-13.json
          requests-14.json
          requests-15.json
          requests-16.json
          ... 1 more files
      26/
        mara-log/
          requests-08.json
          requests-09.json
          requests-11.json
          requests-12.json
          requests-13.json
          requests-14.json
          requests-15.json
          requests-16.json
      29/
        mara-log/
          requests-09.json
          requests-10.json
          requests-11.json
          requests-12.json
          requests-13.json
          requests-14.json
          requests-15.json
          requests-16.json
          requests-17.json
      30/
        mara-log/
          requests-10.json
          requests-11.json
          requests-12.json
          requests-13.json
          requests-14.json
          requests-15.json
          requests-16.json
          requests-17.json
          requests-18.json
      31/
        mara-log/
          requests-08.json
          requests-09.json
          requests-10.json
          requests-11.json
          requests-12.json
          requests-13.json
          requests-14.json
          requests-15.json
          requests-17.json
          requests-18.json
          ... 1 more files
    11/
      01/
        mara-log/
          requests-07.json
          requests-08.json
          requests-09.json
          requests-10.json
          requests-11.json
          requests-12.json
          requests-13.json
          requests-14.json
          requests-15.json
          requests-16.json
          ... 1 more files
      02/
        mara-log/
          requests-07.json
          requests-08.json
          requests-09.json
          requests-10.json
          requests-11.json
          requests-12.json
          requests-13.json
          requests-14.json
          requests-15.json
          requests-16.json
          ... 1 more files
      04/
        mara-log/
          requests-14.json
          requests-15.json
      05/
        mara-log/
          requests-09.json
          requests-10.json
          requests-11.json
          requests-12.json
          requests-13.json
          requests-14.json
          requests-15.json
          requests-16.json
          requests-17.json
          requests-18.json
          ... 2 more files
      06/
        mara-log/
          requests-08.json
          requests-09.json
          requests-10.json
          requests-11.json

now it looks ok

In [9]:
df = pd.read_parquet('data/interim/dashboard_events.parquet')
df

,timestamp,user,method,endpoint,status,dashboard_id,path,browser,browser_platform,browser_version,date
0,2018-08-09 14:00:00.000000,b1fababf379ab3d8@project-a.com,GET,dashboards.view_dashboard,200,marketing-overview,/dashboards/marketing-overview,chrome,macos,67.0.3396.99,2018-08-09
1,2018-08-09 14:00:00.000000,b1fababf379ab3d8@project-a.com,GET,dashboards.view_dashboard,200,marketing-overview,/dashboards/marketing-overview,chrome,macos,67.0.3396.99,2018-08-09
2,2018-08-09 14:00:00.000000,b1fababf379ab3d8@project-a.com,GET,dashboards.view_dashboard,200,marketing-overview,/dashboards/marketing-overview,chrome,macos,67.0.3396.99,2018-08-09
3,2018-08-09 14:00:00.000000,b1fababf379ab3d8@project-a.com,GET,dashboards.view_dashboard,200,marketing-overview,/dashboards/marketing-overview,chrome,macos,67.0.3396.99,2018-08-09
4,2018-08-09 14:00:00.000000,b1fababf379ab3d8@project-a.com,GET,dashboards.view_dashboard,200,marketing-overview,/dashboards/marketing-overview,chrome,macos,67.0.3396.99,2018-08-09
...,...,...,...,...,...,...,...,...,...,...,...
69147,2021-01-10 14:18:03.587892,9942c672b9354771@lampenwelt.de,GET,dashboards.view_dashboard,200,revenue-factura,/dashboards/revenue-factura,chrome,windows,87.0.4280.88,2021-01-10
69148,2021-01-10 14:19:02.411386,9942c672b9354771@lampenwelt.de,GET,dashboards.view_dashboard,200,sales-comparison,/dashboards/sales-comparison,chrome,windows,87.0.4280.88,2021-01-10
69149,2021-01-10 16:00:06.753419,91ec8c4f7243bd8d@lampenwelt.de,GET,dashboards.view_dashboard,200,weekly-sales-comparison,/dashboards/weekly-sales-comparison,chrome,windows,87.0.4280.88,2021-01-10
69150,2021-01-10 17:02:41.778970,27707832861149d0@lampenwelt.de,GET,dashboards.view_dashboard,200,sales-comparison,/dashboards/sales-comparison,chrome,macos,88.0.4324.50,2021-01-10
69151,2021-01-10 17:04:16.000353,dbf168a72424e699@lights.co.uk,GET,dashboards.view_dashboard,200,sales-comparison,/dashboards/sales-comparison,chrome,windows,87.0.4280.88,2021-01-10